# Indexing and slicing of arrays

## Indexing of arrays

Indexing arrays works just as with Python lists, using square brackets and starting with the offset in zero. For multidimensional arrays, you access items using a comma-separated tuple of indices. You can change the array by asigning new values with the index notation.

In [2]:
import numpy as np

x = np.random.randint(10, size=(3,4))
x

array([[5, 0, 1, 4],
       [4, 8, 5, 4],
       [7, 5, 0, 0]])

In [13]:
x[2,1]

5

In [14]:
x[2,1] = 25
x

array([[ 5,  0,  1,  4],
       [ 4,  8,  5,  4],
       [ 7, 25,  0,  0]])

## Array slicing and accessing subarrays

The NumPy slicing syntax follows that of the standard Python list; to access a slice of
an array x, use this:

x[start:stop:step]

_step_ can also be negative for reversing an array.

Multidimensional slices work in the same way, with multiple slices separated by commas.

In [15]:
x[:2,::-1]

array([[4, 1, 0, 5],
       [4, 5, 8, 4]])

Of course, this can be also used for accessing single rows or columns, by combining indexing and slicing

In [16]:
x[:,1]

array([ 0,  8, 25])

In [17]:
x[1,:]

array([4, 8, 5, 4])

One important feature of the Numpy Arrays is that unlike Python lists, slicing pieces of the array returns _views_ rather than _copies_ of the array data.

In [19]:
print(x)
x1 = x[:2,:3]
x1

[[ 5  0  1  4]
 [ 4  8  5  4]
 [ 7 25  0  0]]


array([[5, 0, 1],
       [4, 8, 5]])

In [20]:
x1[1,1]=12 # changing the slice changes the  original matrix
print(x1)
print()
print(x)

[[ 5  0  1]
 [ 4 12  5]]

[[ 5  0  1  4]
 [ 4 12  5  4]
 [ 7 25  0  0]]


For obtaining a copy of the data within an array or subarray we can use the _copy()_ method.

In [21]:
print(x)
x2 = x[:2,:3].copy()
x2

[[ 5  0  1  4]
 [ 4 12  5  4]
 [ 7 25  0  0]]


array([[ 5,  0,  1],
       [ 4, 12,  5]])

In [24]:
x2[1,1]=99 # original not affected
print(x2)
print()
print(x)

[[ 5  0  1]
 [ 4 99  5]]

[[ 5  0  1  4]
 [ 4 12  5  4]
 [ 7 25  0  0]]


In [3]:
a = np.array([n for n in range(10)])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a[1:-1] # go from second element to the last (excluded)
a[-1:1:-1] # from last (included) element to first (excluded) 
a[-1:1] #  start index -1 is greater than the end index 1, resulting in an empty slice

array([], dtype=int64)